/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.mysql.mysql.connector.java)
    api(libs.com.zaxxer.hikaricp)
    api(libs.org.apache.logging.log4j.log4j.api)
    api(libs.org.apache.logging.log4j.log4j.core)
    api(libs.org.apache.logging.log4j.log4j.slf4j.impl)
    api(libs.javax.servlet.jstl)
    api(libs.commons.codec.commons.codec)
    api(libs.org.apache.pdfbox.pdfbox)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.junit.platform.junit.platform.suite.api)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    providedCompile(libs.javax.servlet.javax.servlet.api)
    providedCompile(libs.javax.servlet.jsp.javax.servlet.jsp.api)
    providedCompile(libs.org.projectlombok.lombok)
}

group = "com.hospital.app"
version = "1.0-SNAPSHOT"
description = "Hospital Maven Webapp"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
